version: '3'

networks:
  remb:
    driver: bridge
services:
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - "./redis:/data"
    networks:
      remb:
        aliases:
          - "redis"

  mysql:
    image: mysql
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - 3306:3306
    env_file:
      - .env.mysql
    networks:
      remb:
        aliases:
          - "mysql"

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
    restart: always
    ports:
      - "82:80"
    networks:
      remb:
        aliases:
          - "phpmyadmin"

  
  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "8083:8080"
    environment:
      URL: http://10.59.4.16:8000/api-docs.json
      # API_URL: ""
    networks:
      remb:
        aliases:
          - "swagger"


  api:
    build: .
    command: sh -c "npm install nodemon -g && nodemon ."
    volumes:
      - .:/usr/app
    ports:
      - ${PORT_SERVER}:${PORT_SERVER}
    env_file:
      - .env
      - .env.mysql
      - .env.redis
    depends_on:
      - mysql
    networks:
      remb:
        aliases:
          - "api"